language: csharp
mono:
  - alpha
solution: GestureRecognition.sln
install:
  - nuget restore GestureRecognition.sln
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release GestureRecognition.sln
  - mono ./packages/xunit.runner.console.2.0.0/tools/xunit.console.exe  ./GestureRecognitionTest/bin/Release/GestureRecognitionTest.dll -noshadow