language: csharp
mono:
  - latest
solution: GestureRecognition.sln
install:
  - nuget restore GestureRecognition.sln
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release /p:DebugSymbols=False /p:TargetFrameworkVersion="v4.5 GestureRecognition.sln
  - mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.clr4.exe ./GestureRecognitionTest/bin/Release/GestureRecognitionTest.dll