language: csharp
mono:
  - alpha
env: VERSION=0.1.6
solution: GestureRecognition.sln
before_install:
  - sudo apt-get install nunit-console
install:
  - nuget restore GestureRecognition.sln
script:
  - xbuild /p:Configuration=Release GestureRecognition.sln
after_script:
  - nunit-console Tests/bin/Release/GestureRecognition.dll
deploy:
  provider: script
  skip_cleanup: true
  script:
    - cd GestureRecognition && nuget pack GestureRecognition.nuspec -Version $VERSION -IncludeReferencedProjects -Prop Configuration=Release && nuget push *.nupkg $NUGET_API_KEY -verbosity detailed
  on:
    branch: master
